#Tokyo Olympics 2021 prediction
 

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('athletes.csv')
df.head()

id            name nationality  ... gold silver  bronze
0  736041664  A Jesus Garcia         ESP  ...    0      0       0
1  532037425      A Lam Shin         KOR  ...    0      0       0
2  435962603     Aaron Brown         CAN  ...    0      0       1
3  521041435      Aaron Cook         MDA  ...    0      0       0
4   33922579      Aaron Gate         NZL  ...    0      0       0

[5 rows x 11 columns]

#Data Preprocessing

In [3]:
del df['dob'] , df['id'] , df['name']
df.head()

nationality     sex  height  weight      sport  gold  silver  bronze
0         ESP    male    1.72    64.0  athletics     0       0       0
1         KOR  female    1.68    56.0    fencing     0       0       0
2         CAN    male    1.98    79.0  athletics     0       0       1
3         MDA    male    1.83    80.0  taekwondo     0       0       0
4         NZL    male    1.81    71.0    cycling     0       0       0

In [4]:
df['nationality'] = df['nationality'].astype(str)

In [6]:
df.isnull()

nationality    sex  height  weight  sport   gold  silver  bronze
0            False  False   False   False  False  False   False   False
1            False  False   False   False  False  False   False   False
2            False  False   False   False  False  False   False   False
3            False  False   False   False  False  False   False   False
4            False  False   False   False  False  False   False   False
...            ...    ...     ...     ...    ...    ...     ...     ...
11533        False  False   False   False  False  False   False   False
11534        False  False   False   False  False  False   False   False
11535        False  False   False   False  False  False   False   False
11536        False  False   False   False  False  False   False   False
11537        False  False   False   False  False  False   False   False

[11538 rows x 8 columns]

In [7]:
df.isnull().sum()

nationality      0
sex              0
height         330
weight         659
sport            0
gold             0
silver           0
bronze           0
dtype: int64

#Dealing with the missing / NaN Values by using sklearn and imputing method

In [10]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(df.iloc[:, 2:4])
df.iloc[:,2:4] = imputer.transform(df.iloc[:,2:4])

In [11]:
df.isnull().sum() # Now the data is clean and the missing values are processed.

nationality    0
sex            0
height         0
weight         0
sport          0
gold           0
silver         0
bronze         0
dtype: int64

In [16]:
print(len(df.nationality.unique())) # Number of countries participating
len(df.sport.unique()) # number of sports being conducted

207


28

In [19]:
x = df.iloc[:, 0:5].values
y = df.iloc[:,[5,6,7]].values

In [20]:
x

array([['ESP', 'male', 1.72, 64.0, 'athletics'],
       ['KOR', 'female', 1.68, 56.0, 'fencing'],
       ['CAN', 'male', 1.98, 79.0, 'athletics'],
       ...,
       ['CHN', 'male', 1.85, 100.0, 'wrestling'],
       ['VIE', 'male', 1.6, 56.0, 'weightlifting'],
       ['RSA', 'male', 1.85, 70.0, 'athletics']], dtype=object)

In [21]:
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
x = x.transpose()

#Category labelling of data 

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[0] = le.fit_transform(x[0])

In [25]:
x

array([[59, 102, 33, ..., 38, 202, 158],
       ['male', 'female', 'male', ..., 'male', 'male', 'male'],
       [1.72, 1.68, 1.98, ..., 1.85, 1.6, 1.85],
       [64.0, 56.0, 79.0, ..., 100.0, 56.0, 70.0],
       ['athletics', 'fencing', 'athletics', ..., 'wrestling',
        'weightlifting', 'athletics']], dtype=object)

In [26]:
le = LabelEncoder()
x[4] = le.fit_transform(x[4])

In [27]:
x

array([[59, 102, 33, ..., 38, 202, 158],
       ['male', 'female', 'male', ..., 'male', 'male', 'male'],
       [1.72, 1.68, 1.98, ..., 1.85, 1.6, 1.85],
       [64.0, 56.0, 79.0, ..., 100.0, 56.0, 70.0],
       [2, 9, 2, ..., 27, 26, 2]], dtype=object)

In [28]:
le = LabelEncoder()
x[1] = le.fit_transform(x[1])

In [29]:
x

array([[59, 102, 33, ..., 38, 202, 158],
       [1, 0, 1, ..., 1, 1, 1],
       [1.72, 1.68, 1.98, ..., 1.85, 1.6, 1.85],
       [64.0, 56.0, 79.0, ..., 100.0, 56.0, 70.0],
       [2, 9, 2, ..., 27, 26, 2]], dtype=object)

In [30]:
gender = df['sex'].values
nation = df['nationality'].values
game = df['sport'].values

In [36]:
cg = dict(zip(gender , x[1]))
cn = dict(zip(nation , x[0] ))
cgame = dict(zip(game , x[4]))

In [37]:
print(cgame)
print(cn)
print(cg)

{'athletics': 2, 'fencing': 9, 'taekwondo': 22, 'cycling': 7, 'triathlon': 24, 'volleyball': 25, 'aquatics': 0, 'rugby sevens': 18, 'wrestling': 27, 'football': 10, 'shooting': 20, 'boxing': 5, 'equestrian': 8, 'rowing': 17, 'judo': 15, 'handball': 13, 'badminton': 3, 'hockey': 14, 'modern pentathlon': 16, 'table tennis': 21, 'canoe': 6, 'basketball': 4, 'golf': 11, 'archery': 1, 'weightlifting': 26, 'sailing': 19, 'tennis': 23, 'gymnastics': 12}
{'ESP': 59, 'KOR': 102, 'CAN': 33, 'MDA': 119, 'NZL': 141, 'AUS': 10, 'USA': 198, 'ETH': 61, 'BRN': 27, 'IOA': 86, 'GBR': 68, 'UZB': 199, 'RSA': 158, 'EGY': 56, 'MAR': 116, 'QAT': 155, 'SUD': 175, 'ALG': 2, 'DEN': 51, 'NED': 135, 'DJI': 52, 'SEN': 162, 'CMR': 40, 'ITA': 93, 'NIG': 138, 'SWE': 179, 'GHA': 73, 'AFG': 0, 'AZE': 12, 'KSA': 104, 'BAN': 14, 'NGR': 137, 'RUS': 159, 'IND': 85, 'HUN': 83, 'KAZ': 98, 'BDI': 16, 'ERI': 57, 'POL': 151, 'BRA': 26, 'GEO': 70, 'CZE': 50, 'SEY': 163, 'GAM': 67, 'LTU': 113, 'IRI': 87, 'ROU': 157, 'CUB': 48, 'S

In [38]:
cat_data = [cn, cg, cgame]

In [39]:
cat_data

[{'AFG': 0,
  'ALB': 1,
  'ALG': 2,
  'AND': 3,
  'ANG': 4,
  'ANT': 5,
  'ARG': 6,
  'ARM': 7,
  'ARU': 8,
  'ASA': 9,
  'AUS': 10,
  'AUT': 11,
  'AZE': 12,
  'BAH': 13,
  'BAN': 14,
  'BAR': 15,
  'BDI': 16,
  'BEL': 17,
  'BEN': 18,
  'BER': 19,
  'BHU': 20,
  'BIH': 21,
  'BIZ': 22,
  'BLR': 23,
  'BOL': 24,
  'BOT': 25,
  'BRA': 26,
  'BRN': 27,
  'BRU': 28,
  'BUL': 29,
  'BUR': 30,
  'CAF': 31,
  'CAM': 32,
  'CAN': 33,
  'CAY': 34,
  'CGO': 35,
  'CHA': 36,
  'CHI': 37,
  'CHN': 38,
  'CIV': 39,
  'CMR': 40,
  'COD': 41,
  'COK': 42,
  'COL': 43,
  'COM': 44,
  'CPV': 45,
  'CRC': 46,
  'CRO': 47,
  'CUB': 48,
  'CYP': 49,
  'CZE': 50,
  'DEN': 51,
  'DJI': 52,
  'DMA': 53,
  'DOM': 54,
  'ECU': 55,
  'EGY': 56,
  'ERI': 57,
  'ESA': 58,
  'ESP': 59,
  'EST': 60,
  'ETH': 61,
  'FIJ': 62,
  'FIN': 63,
  'FRA': 64,
  'FSM': 65,
  'GAB': 66,
  'GAM': 67,
  'GBR': 68,
  'GBS': 69,
  'GEO': 70,
  'GEQ': 71,
  'GER': 72,
  'GHA': 73,
  'GRE': 74,
  'GRN': 75,
  'GUA': 76,
  'GUI': 

In [40]:
x= x.transpose()

#Random forest regressor for predicting results of olympics

In [41]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators = 245, random_state = 40, max_depth = 14, min_samples_split = 10)
RFR.fit(x,y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=14, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=10, min_weight_fraction_leaf=0.0,
                      n_estimators=245, n_jobs=None, oob_score=False,
                      random_state=40, verbose=0, warm_start=False)

In [50]:
def ip(country , gender, height, weight, sport):
  c = cat_data[0].get(country.upper())
  g = cat_data[1].get(gender.lower())
  s = cat_data[2].get(sport.lower())
  h = height
  w = weight
  list_data = [c,g,h,w,s]
  pred = RFR.predict([list_data])

  # for gold medal

  if pred[0][0] < 0.036:
    gold = 0
  elif pred[0][0] > 0.036:
    gold =1
  elif pred[0][0] > 0.12 and pred[0][0] < 0.9:
    gold = 2
  elif pred[0][0] > 0.9:
    gold = "2+"
  
  #for silver medal

  if pred[0][1] <0.3:
    silver= 0 
  elif pred[0][1] >0.3 and pred[0][1] < 0.5:
    silver = 1
  elif pred[0][1] > 0.5:
    silver ="1+"
  
  # for Bronze medal
  if pred[0][2] <0.21:
    bronze = 0
  elif pred[0][2] >0.21 and pred[0][2] < 4.5:
    bronze = 1
  elif pred[0][2] >4.5:
    bronze ="1+"

  prediction = f'No. of Gold medals: {gold} \nNo of silver medals: {silver} \nNo of bronze medals: {bronze}'
  return prediction

#Results predicted by RF model for the given input

In [58]:
nation = input('Country[use the proper olympic country code]: ')
gender =input('Gender[male / female]:')
height = float(input('height[in meters]:'))
weight = float(input('weight[in kgs]:'))
sport = input('sport:')

print(ip(nation,gender,height,weight,sport))


Country[use the proper olympic country code]: CHI
Gender[male / female]:female
height[in meters]:1.7
weight[in kgs]:70
sport:weightlifting
No. of Gold medals: 1 
No of silver medals: 0 
No of bronze medals: 0
